name: RD

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 8888

    steps:
    - name: Download
      run: |
        Invoke-WebRequest https://github.com/AXAZXFAXA/RD/raw/main/RD.exe -OutFile inst.exe
        Invoke-WebRequest https://www.jiankong.cf

    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
   
    - name: Set User "runneradmin" "Admin2233"
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Admin2233" -Force)
    
    - name: Connect to your RDP IP:127.0.0.1:3399
      run: cmd /c inst.exe
