name: SSH

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 8888

    steps:
    - name: Download Frp
      run: wget https://github.com/AXAZXFAXA/RD/blob/main/frpc -O frpc
      
    - name: Make ini
      run: |
        echo [common] >> ./frpc.ini
        echo server_addr = 127.0.0.1 >> ./frpc.ini
        echo server_port = 7000 >> ./frpc.ini
        echo [ssh] >> ./frpc.ini
        echo type = tcp >> ./frpc.ini
        echo local_ip = 127.0.0.1 >> ./frpc.ini
        echo local_port = 22 >> ./frpc.ini
        echo remote_port = 2222 >> ./frpc.ini

    - name: Chmod
      run: sudo chmod 777 ./frpc

    - name: Start
      run: ./frpc -c ./frpc.ini
      
    - name: Set User "runneradmin" "Admin2233"
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Admin2233" -Force)
    
    - name: Connect to your RDP IP:127.0.0.1:3399
      run: Ping 127.0.0.1
