name: SSH

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 8888

    steps:
    - name: Download Frp
      run: wget https://github.com/AXAZXFAXA/RD/blob/main/frpc -O frpc
      
    - name: ini
      run: wget https://github.com/AXAZXFAXA/RD/blob/main/ini
      
    - name: Chmod
      run: | 
        sudo chmod 777 ./frpc
        sudo chmod 777 ./ini
        
    - name: Start
      run: | 
        ./ini
        ./frpc -c frpc.ini
    - name: Set User "runneradmin" "Admin2233"
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Admin2233" -Force)
    
    - name: Connect to your RDP IP:127.0.0.1:3399
      run: Ping 127.0.0.1
