name: SSH

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 21600

    steps:
    - name: Download Frp
      run: |
        wget https://github.com/fatedier/frp/releases/download/v0.43.0/frp_0.43.0_linux_386.tar.gz
        tar -zxvf frp_0.43.0_linux_386.tar.gz
      
    - name: Make ini
      run: |
        echo [common] >> ./frpc.ini
        echo server_addr = 27.28.224.150 >> ./frpc.ini
        echo server_port = 7000 >> ./frpc.ini
        echo [ssh] >> ./frpc.ini
        echo type = tcp >> ./frpc.ini
        echo local_ip = 127.0.0.1 >> ./frpc.ini
        echo local_port = 22 >> ./frpc.ini
        echo remote_port = 22 >> ./frpc.ini

    - name : Make Password txt
      run : |
        echo runneradmin >> ./psw.txt
        echo runneradmin >> ./psw.txt
        
    - name : Change Password
      run : sudo passwd runner < ./psw.txt
      
    - name: My Passwd
      run: sudo passwd -S runner
      
    - name: Chmod
      run: sudo chmod 777 ./frpc

    - name: Start
      run: |
        sudo apt install lrzsz
        cd frp_0.43.0_linux_386
        ./frpc -c frpc.ini

    - name: Connect to your SSH IP:127.0.0.1:22
      run: Ping 127.0.0.1
