name: SSH2

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 8888

    steps:
    - name: Download Frp
      run: wget https://github.com/AXAZXFAXA/RD/blob/main/A -O A
